---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true # Necessário para ufw/systemd
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
