---
- name: "Prepare Host Nodes for Juju Manual Cloud"
  hosts: lxd_hosts
  become: yes
  gather_facts: yes

  tasks:
    - name: "Force Cleanup: Stop services and remove all Juju agent traces from remote host"
      ansible.builtin.shell: |
        set -x
        systemctl stop snap.jujud.daemon.service || true
        systemctl disable snap.jujud.daemon.service || true
        systemctl stop jujud-machine-agent.service || true
        systemctl disable jujud-machine-agent.service || true
        killall -9 jujud || true
        rm -rf /var/lib/juju/*
        rm -rf /etc/juju/*
      changed_when: false

    - name: "Update apt cache"
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

    - name: "Install prerequisite packages"
      ansible.builtin.apt:
        name:
          - python3-pip
          - snapd
          - openssl
        state: present

    - name: "Install or refresh the LXD snap to stable channel"
      ansible.builtin.snap:
        name: lxd
        channel: "5.0/stable"
        state: present

    - name: "Forcefully restart the LXD service"
      ansible.builtin.systemd:
        name: snap.lxd.daemon
        state: restarted
        daemon_reload: yes

    - name: "Wait 20 seconds for service to settle after restart"
      ansible.builtin.pause:
        seconds: 20

    - name: "Wait for LXD socket to be ready"
      ansible.builtin.wait_for:
        path: /var/snap/lxd/common/lxd/unix.socket
        state: present
        delay: 5
        timeout: 300
      changed_when: false

    - name: "Initialize LXD using auto configuration (idempotent)"
      ansible.builtin.command: lxd init --auto
      register: lxd_init
      changed_when: "'LXD has been successfully configured' in lxd_init.stdout"
      retries: 10
      delay: 15
      until: "lxd_init.rc == 0"

    - name: "Install the Juju snap with classic confinement"
      ansible.builtin.snap:
        name: juju
        classic: yes
        state: present

    - name: "Configure LXD default profile to allow nesting"
      ansible.builtin.command: lxc profile set default security.nesting true
      changed_when: false # This command doesn't indicate change, safe to run always

    - name: "Enable IP forwarding for container networking"
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: "!!! LAB ONLY !!! Configure iptables to ACCEPT all forward traffic"
      ansible.builtin.iptables:
        chain: FORWARD
        policy: ACCEPT
        comment: "Allow all forward traffic for Juju lab environment."

    - name: "Add current user to the lxd group for permissions"
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: lxd
        append: yes
      
    - name: "Reset SSH connection to apply group changes"
      ansible.builtin.meta: reset_connection
