---
- name: Prepare Base VMs
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure python3 is present for Ansible
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt-get update && apt-get install -y python3-minimal)
      changed_when: false

    - name: Update APT cache and install required packages
      ansible.builtin.apt:
        name: ["snapd", "python3-pip"]
        update_cache: yes
        state: present