---
- name: Setup LXD
  hosts: all
  become: yes

  collections:
    - community.general

  tasks:
    - name: Install LXD from snap
      ansible.builtin.snap:
        name: lxd
      
    - name: Initialize LXD (non-interactive) if not already done
      ansible.builtin.command: lxd init --auto
      args:
        creates: /var/snap/lxd/common/lxd/lxd.db # Check for the database file to ensure idempotency
      register: lxd_init_result
      changed_when: "'LXD has been successfully configured' in lxd_init_result.stdout"

    - name: "Disable IPv6 on the default LXD bridge (lxdbr0)"
      ansible.builtin.command:
        cmd: lxc network set lxdbr0 ipv6.address none
      changed_when: true # O comando é idempotente por natureza, mas indicamos mudança para clareza.

    - name: Ensure ansible user is in the lxd group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: lxd
        append: yes