---
- name: Add LXC Machines to Model
  hosts: "{{ groups['lxd_hosts'][0] }}"
  gather_facts: no
  become: no
  when: "groups['lxd_hosts'] | length > 1"

  tasks:
    - name: Add 3 LXC machines to node 0
      command: "/snap/bin/juju add-machine lxd:0 -n 3 -m {{ controller_name }}:{{ model_name }}"
      changed_when: true

    - name: Add 3 LXC machines to node 1
      command: "/snap/bin/juju add-machine lxd:1 -n 3 -m {{ controller_name }}:{{ model_name }}"
      changed_when: true
