---
- name: Deploy Landscape Services to HA Cluster
  hosts: "{{ groups['lxd_hosts'][0] }}"
  become: no
  gather_facts: no

  tasks:
    - name: Deploy PostgreSQL to a new container on machine 0
      ansible.builtin.command: "juju deploy postgresql --channel 14/stable --to lxc@0"
      changed_when: true

    - name: Deploy RabbitMQ to a new container on machine 1
      ansible.builtin.command: "juju deploy rabbitmq-server --channel 3.9/stable --to lxc@1"
      changed_when: true

    - name: Deploy HAProxy to a new container on machine 0
      ansible.builtin.command: "juju deploy haproxy --channel stable --to lxc@0"
      changed_when: true

    - name: Deploy another HAProxy to a new container on machine 1
      ansible.builtin.command: "juju deploy haproxy --channel stable --to lxc@1"
      changed_when: true

    - name: Deploy Landscape Server to a new container on machine 0
      ansible.builtin.command: "juju deploy landscape-server --channel stable --to lxc@0"
      changed_when: true

    - name: Deploy another Landscape Server to a new container on machine 1
      ansible.builtin.command: "juju deploy landscape-server --channel stable --to lxc@1"
      changed_when: true

    - name: Wait for all applications to be ready
      ansible.builtin.command: "juju wait-for application -m {{ model_name }} --query=\"status=='active'\""
      changed_when: false
      timeout: 1800 # 30 minute timeout

    - name: Relate Landscape Server to PostgreSQL
      ansible.builtin.command: "juju relate landscape-server:db postgresql:db"
      changed_when: true

    - name: Relate Landscape Server to RabbitMQ
      ansible.builtin.command: "juju relate landscape-server rabbitmq-server"
      changed_when: true

    - name: Relate HAProxy to Landscape Server
      ansible.builtin.command: "juju relate haproxy landscape-server"
      changed_when: true