---
- name: Deploy Canonical Landscape Application (Sequential Strategy)
  hosts: all
  become: no # Juju commands run as the user
  gather_facts: no

  vars:
    overlay_path: "{{ playbook_dir }}/../landscape_overlay.yaml"
    cert_path: "/tmp/landscape_cert.pem"
    key_path: "/tmp/landscape_key.pem"
    cert_cn: "{{ domain_name | default('landscape.test.local') }}"

  tasks:
    - name: Generate a self-signed certificate and private key
      ansible.builtin.command:
        cmd: >
          openssl req -new -x509 -nodes -days 365
          -subj "/CN={{ cert_cn }}"
          -out "{{ cert_path }}"
          -keyout "{{ key_path }}"
      args:
        creates: "{{ cert_path }}"

    - name: Read and b64encode certificate
      ansible.builtin.set_fact:
        cert_content_b64: "{{ (lookup('file', cert_path) + '\n') | b64encode }}"

    - name: Read and b64encode private key
      ansible.builtin.set_fact:
        key_content_b64: "{{ lookup('file', key_path) | b64encode }}"

    - name: Create Juju overlay file for SSL
      ansible.builtin.copy:
        dest: "{{ overlay_path }}"
        content: |
          applications:
            haproxy:
              options:
                ssl_cert: {{ cert_content_b64 }}
                ssl_key: {{ key_content_b64 }}

    - name: Check for available models
      ansible.builtin.command: sg lxd -c "juju models --format=json"
      register: juju_models_json
      changed_when: false
      become: no
      ignore_errors: true

    - name: Set list of model names
      ansible.builtin.set_fact:
        model_names: "{{ (juju_models_json.stdout | from_json).models | map(attribute='name') | list }}"
      when: juju_models_json.stdout != ""

    - name: Add a model for the landscape application
      ansible.builtin.command: "sg lxd -c 'juju add-model {{ model_name }}'"
      when: model_name not in model_names
      changed_when: true
      become: no

    - name: Deploy Landscape via official stable bundle
      when: not (is_ha_cluster | bool)
      ansible.builtin.command: "sg lxd -c 'juju deploy -m {{ model_name }} landscape-scalable --channel=stable --overlay {{ overlay_path }}'"
      changed_when: true

    # --- BLOCK FOR HA (PRODUCTION) - Not refactored, will be skipped ---
    - name: Deploy for HA Cluster (Production Environment)
      ansible.builtin.command:
        cmd: "sg lxd -c 'juju deploy -m {{ model_name }} ./juju/bundle-base.yaml --overlay ./juju/overlay-ha.yaml --overlay {{ overlay_path }}'"
      args:
        chdir: /home/ubuntu/projetos/landscape-automation
      when: is_ha_cluster | bool
      register: juju_deploy_ha_result
      changed_when: "'Deploying' in juju_deploy_ha_result.stdout"