---
- name: Apply PFX Certificate to HAProxy
  hosts: "{{ groups['lxd_hosts'][0] }}"
  gather_facts: no
  vars:
    juju_model: "controller" # Substitua pelo nome do seu modelo Juju
    juju_application: "haproxy"
    certificate_path: "/path/to/your/certificate.pfx" # Substitua pelo caminho real do seu certificado PFX
    certificate_password: "your_certificate_password" # Substitua pela senha do seu certificado PFX

  tasks:
    - name: Ensure Juju is logged in
      command: juju status
      register: juju_status_result
      failed_when: "'not logged in' in juju_status_result.stderr"
      changed_when: false

    - name: Convert PFX to PEM (key and cert)
      ansible.builtin.shell: |
        openssl pkcs12 -in {{ certificate_path }} -nocerts -nodes -passin pass:{{ certificate_password }} | openssl rsa > /tmp/haproxy.key
        openssl pkcs12 -in {{ certificate_path }} -nokeys -out /tmp/haproxy.crt -passin pass:{{ certificate_password }}
      args:
        creates: /tmp/haproxy.key
      changed_when: true

    - name: Upload certificate and key to HAProxy application
      command: >
        juju run --model {{ juju_model }} --application {{ juju_application }}
        "set-ssl-cert key="$(cat /tmp/haproxy.key)" cert="$(cat /tmp/haproxy.crt)""
      changed_when: true

    - name: Clean up temporary certificate files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/haproxy.key
        - /tmp/haproxy.crt
      changed_when: true
