---
- name: Verify Juju Model Health and Provide Next Steps
  hosts: all
  gather_facts: no
  connection: local

  vars:
    health_check_retries: 240 # 60 minutes (240 retries * 15 seconds)
    health_check_delay: 15

  tasks:
    - name: Wait for applications to become active
      ansible.builtin.shell:
        cmd: "sg lxd -c 'juju status --format=json' | /usr/bin/python3 health_check.py"
      args:
        executable: /bin/bash
        chdir: "{{ playbook_dir }}"
      register: health_check_result
      until: health_check_result.rc == 0
      retries: "{{ health_check_retries }}"
      delay: "{{ health_check_delay }}"
      changed_when: false
      ignore_errors: true # We check the final status manually

    - name: Set final health status fact
      ansible.builtin.set_fact:
        all_apps_active: "{{ health_check_result.rc == 0 }}"

    - name: Get final Juju status for IP address
      ansible.builtin.command: "sg lxd -c 'juju status --format=json'"
      register: final_juju_status
      changed_when: false
      when: all_apps_active

    - name: Display SUCCESS and Next Steps
      when: all_apps_active
      block:
        - name: Set HAProxy IP Address
          ansible.builtin.set_fact:
            haproxy_ip: "{{ ((final_juju_status.stdout | from_json).applications.haproxy.units['haproxy/0'])['public-address'] }}"

        - name: Display Final Instructions
          ansible.builtin.debug:
            msg: |
              ######################################################################
              #      IMPLANTAÇÃO CONCLUÍDA COM SUCESSO!                            #
              ######################################################################

              O ambiente do Landscape está pronto.

              PRÓXIMOS PASSOS:
              1. Abra um navegador e acesse a URL: https://{{ haproxy_ip }}/

              2. Você verá um aviso de segurança sobre o certificado. Isso é
                 ESPERADO, pois usamos um certificado autoassinado. Aceite o
                 risco e continue para o site.

              3. Siga as instruções no portal do Landscape para criar o
                 primeiro administrador e registrar seus servidores.

              ######################################################################

    - name: Display TIMEOUT Message
      when: not all_apps_active
      ansible.builtin.debug:
        msg: |
          ######################################################################
          #      A IMPLANTAÇÃO NÃO FOI CONCLUÍDA COM SUCESSO.                #
          ######################################################################

          Ocorreu um timeout após {{ health_check_retries * health_check_delay / 60 }} minutos.
          Use a opção "Verificar Status do Ambiente" no menu principal para investigar.
