---
- name: Clean Juju Agent State from Hosts
  hosts: lxd_hosts
  become: yes
  gather_facts: no

  tasks:
    - name: "Run remove-juju-services script to clean agent state"
      ansible.builtin.command: "sudo /usr/sbin/remove-juju-services"
      changed_when: true
      ignore_errors: true # This script might fail if there's nothing to remove, which is ok.

    - name: "Ensure Juju snap is reinstalled for a clean client state"
      ansible.builtin.snap:
        name: juju
        classic: yes
        state: present