---
- name: Nuclear Cleanup of Juju State on All Hosts
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: "Perform aggressive cleanup of Juju processes, snaps, and directories"
      ansible.builtin.shell: |
        sudo pkill -9 jujud juju mongod 2>/dev/null || true
        sleep 2
        sudo snap remove juju --purge juju-db --purge 2>/dev/null || true
        sleep 5
        sudo rm -rf /var/lib/juju /var/run/juju /var/cache/juju /var/snap/juju* 2>/dev/null || true
        rm -rf ~/.local/share/juju ~/.juju ~/.cache/juju 2>/dev/null || true
      changed_when: true

    - name: "Check if /usr/sbin/remove-juju-services script exists"
      ansible.builtin.stat:
        path: /usr/sbin/remove-juju-services
      register: remove_juju_services_script

    - name: "Execute /usr/sbin/remove-juju-services if it exists"
      ansible.builtin.command: "sudo /usr/sbin/remove-juju-services"
      changed_when: true
      ignore_errors: true
      when: remove_juju_services_script.stat.exists

    - name: "Ensure Juju snap is installed/reinstalled for a clean client state"
      ansible.builtin.snap:
        name: juju
        classic: yes
        state: present