---
# playbooks/juju-ha-validate.yml
# Validar e reportar status do cluster Juju HA após bootstrap

- name: Validate Juju HA Cluster Status
  hosts: ha_nodes
  serial: 1
  remote_user: serpro
  gather_facts: yes
  
  vars:
    controller_name: "ha-controller"

  pre_tasks:
    - name: Verify connectivity
      ping: 

    - name: Set dynamic variables
      set_fact:
        juju_data_dir: "{{ ansible_user_dir }}/.local/share/juju"

    - name: Display node info
      debug:
        msg: |
          Node: {{ inventory_hostname }}
          IP: {{ ansible_host }}
          User: {{ ansible_user }}
          Juju Dir: {{ juju_data_dir }}

  tasks:
    # ============================================ 
    # 1. VALIDAR CONTROLLER
    # ============================================ 
    - name: Check Juju Controller Status
      block:
        - name: Get controllers list
          shell: |
            export JUJU_DATA={{ juju_data_dir }}
            juju controllers
          environment:
            JUJU_DATA: "{{ juju_data_dir }}"
          register: controllers_status
          changed_when: false

        - name: Display controller status
          debug:
            msg: |
              ╔════════════════════════════════════════╗
              ║  JUJU CONTROLLER STATUS                ║
              ╚════════════════════════════════════════╝
              {{ controllers_status.stdout }}
          when: inventory_hostname == "ha-node-01"

      when: inventory_hostname == "ha-node-01"
      tags: validate_controller

    # ============================================ 
    # 2. VALIDAR MÁQUINAS
    # ============================================ 
    - name: Check Juju Machines
      block:
        - name: Get machines in controller model
          shell: |
            export JUJU_DATA={{ juju_data_dir }}
            juju machines -m controller 2>/dev/null || echo "Model not ready"
          environment:
            JUJU_DATA: "{{ juju_data_dir }}"
          register: machines_controller
          changed_when: false

        - name: Display machines status
          debug:
            msg: |
              ╔════════════════════════════════════════╗
              ║  JUJU MACHINES (controller model)       ║
              ╚════════════════════════════════════════╝
              {{ machines_controller.stdout }}
          when: inventory_hostname == "ha-node-01"

      when: inventory_hostname == "ha-node-01"
      tags: validate_machines

    # ============================================ 
    # 3. VALIDAR LXD BRIDGES
    # ============================================ 
    - name: Check LXD Configuration
      block:
        - name: Get LXD bridges
          shell: lxc network list
          register: lxd_networks
          changed_when: false

        - name: Display LXD networks
          debug:
            msg: |
              ╔════════════════════════════════════════╗
              ║  LXD NETWORKS ({{ inventory_hostname }})   ║
              ╚════════════════════════════════════════╝
              {{ lxd_networks.stdout }}

      tags: validate_lxd

    # ============================================ 
    # 4. VALIDAR SSH CONECTIVIDADE ENTRE NÓS
    # ============================================ 
    - name: Validate Inter-Node Connectivity
      block:
        - name: Test SSH to other node
          shell: |
            if [ "{{ inventory_hostname }}" = "ha-node-01" ]; then
              ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 \
                  serpro@10.35.0.10 "echo ✓ SSH OK to ha-node-02"
            else
              ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 \
                  serpro@10.35.0.9 "echo ✓ SSH OK to ha-node-01"
            fi
          register: inter_node_ssh
          changed_when: false
          ignore_errors: true

        - name: Display inter-node connectivity
          debug:
            msg: |
              ╔════════════════════════════════════════╗
              ║  INTER-NODE CONNECTIVITY                ║
              ║  From: {{ inventory_hostname }}
              ╚════════════════════════════════════════╝
              {{ inter_node_ssh.stdout }}
              Return code: {{ inter_node_ssh.rc }}

      tags: validate_connectivity

    # ============================================ 
    # 5. VALIDAR RECURSOS DO NÓ
    # ============================================ 
    - name: Validate Node Resources
      block:
        - name: Get CPU info
          shell: nproc
          register: cpu_count
          changed_when: false

        - name: Get memory info
          shell: free -h | grep Mem
          register: mem_info
          changed_when: false

        - name: Get disk info
          shell: df -h / | tail -1
          register: disk_info
          changed_when: false

        - name: Display resources
          debug:
            msg: |
              ╔════════════════════════════════════════╗
              ║  NODE RESOURCES ({{ inventory_hostname }})  ║
              ╚════════════════════════════════════════╝
              CPU Cores: {{ cpu_count.stdout }}
              
              Memory:
              {{ mem_info.stdout }}
              
              Disk:
              {{ disk_info.stdout }}

      tags: validate_resources

  post_tasks:
    - name: Generate validation report
      block:
        - name: Collect all status
          shell: |
            export JUJU_DATA={{ juju_data_dir }}
            echo "=== COMPLETE CLUSTER STATUS ==="
            echo ""
            echo "CONTROLLERS:"
            juju controllers
            echo ""
            echo "MACHINES:"
            juju machines -m controller 2>/dev/null || echo "No machines yet"
            echo ""
            echo "MODELS:"
            juju models
            echo ""
            echo "STATUS:"
            juju status -m controller 2>/dev/null | head -30 || echo "Status not available"
          environment:
            JUJU_DATA: "{{ juju_data_dir }}"
          register: complete_status
          changed_when: false
          when: inventory_hostname == "ha-node-01"

        - name: Display final report
          debug:
            msg: |
              ╔════════════════════════════════════════════════════╗
              ║         JUJU HA CLUSTER VALIDATION COMPLETE        ║
              ╚════════════════════════════════════════════════════╝
              
              {{ complete_status.stdout | default('') }}
          when: inventory_hostname == "ha-node-01"

      tags: report
