---
- name: Graceful Destruction
  ansible.builtin.import_playbook: 99-destroy-graceful.yml

- name: Forceful Agent Cleanup
  ansible.builtin.import_playbook: 99-cleanup-agents.yml

- name: "Step X: Verify Host Health After Cleanup"
  hosts: all # Verifica todos os hosts que passaram pela limpeza
  become: yes
  gather_facts: yes # Requer facts para verificar disco/memória
  tasks:
    - name: "Check SSH connectivity (implicit via Ansible connection)"
      ansible.builtin.ping:

    - name: "Check available disk space on root filesystem"
      ansible.builtin.assert:
        that: ansible_mounts | selectattr('mount', 'equalto', '/') | map(attribute='size_available') | first > (10 * 1024 * 1024 * 1024) # Ex: > 10GB free
        fail_msg: "Espaço em disco insuficiente no '/' após a limpeza."
        success_msg: "Espaço em disco OK."

    - name: "Check if LXD service is running (expected after cleanup/prepare)"
      ansible.builtin.service:
        name: snap.lxd.daemon # Nome do serviço snap do LXD
        state: started
        enabled: yes # Verifica se está habilitado também
      register: lxd_service_status
      failed_when: lxd_service_status.state != 'started'

    - name: "Check if Juju snap is present (expected after cleanup)"
      ansible.builtin.command: "snap list juju"
      register: juju_snap_check
      changed_when: false
      failed_when: "'juju' not in juju_snap_check.stdout"

    - name: "Final Health Status Message"
      ansible.builtin.debug:
        msg: "Verificação de saúde pós-limpeza concluída. Host(s) parecem estar em um estado operacional básico."