---
- name: "[PREPARE] Fase 1 - Preparar Nós Remotos (Limpeza Nuclear)"
  import_playbook: 00-prepare-nodes.yml
  tags:
    - prepare
    - full

- name: "[BOOTSTRAP] Fase 2 - Bootstrap do Controller (Execução Local)"
  import_playbook: 01-bootstrap-controller.yml
  tags:
    - bootstrap
    - full